### ISSUE TITLE
Please respect the terms of the MIT License of vscode-ginkgo-tools and keep my copyright notice in the LICENSE file 🙏 

### ISSUE THREAD

**Issue by dlipovetsky** [joselitofilho/ginkgoTestExplorer#34]
Hi @joselitofilho,

I support the work you are doing here, and I thank you for saying in your README that your project is partly based on mine, and for maintaining a link to the [vscode-ginkgo-tools](https://github.com/dlipovetsky/vscode-ginkgo-tools) repository.

However, I humbly ask that you respect the terms of the MIT License under which I licensed my project 🙏.

The [LICENSE](https://github.com/dlipovetsky/vscode-ginkgo-tools/blob/v0.1.0/LICENSE) file in my project says:
> Copyright (c) 2020-2021 Daniel Lipovetsky
...
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Your commit https://github.com/joselitofilho/ginkgoTestExplorer/commit/254edb2c6ce1bafa3f4bceb6fedf37fd28e2e39a includes almost all of the source code files from my project, but my copyright does not appear in the [LICENSE](https://github.com/joselitofilho/ginkgoTestExplorer/commit/d24546937abe3d44e79e91c59a27b1a2cde2728d) file for your project.

Thank you,
Daniel

**Comment by joselitofilho** [comment]
Hi @dlipovetsky, 

Sorry about that. It was my mistake.
What should I write there? Do you mind making the change and opening a PR?

**Comment by joselitofilho** [comment]
@dlipovetsky 

I've opened PR #36 updating the LICENSE. Please, tell me if you agree.

**Comment by joselitofilho** [comment]
Hi @dlipovetsky,

Did you see how the license was?
