### ISSUE TITLE
Unescaped special symbols in test names can lead to arbitrary code execution

### ISSUE THREAD

**Issue by RomanKornev** [joselitofilho/ginkgoTestExplorer#43]
`var _ = Describe("\" any code here gets executed", func() {`

**Comment by joselitofilho** [comment]
Hi @RomanKornev, this problem is related to how ginkgo works. 
Have you used the new version of ginkgo 2 together with the new plugin version 1.0.0?

**Comment by joselitofilho** [comment]
Related with #41
