### ISSUE TITLE
Pass build tags to ginkgo

### ISSUE THREAD

**Issue by MatthewLymer** [joselitofilho/ginkgoTestExplorer#49]
Currently the test explorer has no facility to provide build tags when invoking the `ginkgo` binary.

This causes a problem for my team as we'd like to run e2e tests but they're only compiled when the e2e tag is provided

```go
//go:build e2e

// ...

_ = Describe("Please pass", func () {
  It("Should pass", func () {
    Expect(true).To(BeTrue())
  });
});
```

However, when executing this test via the test explorer, it says no specs are found, because it's not compiled due to the tag not being set.

I'm wondering whether the `settings.json` property `"go.testTags"` could be read by the test explorer, or be able to provide its own.

**Comment by rufreakde** [comment]
Bump this `go.testTags` in vs code why not use it. And it is helping tremendously organising your test code.

**Comment by darky** [comment]
I'am surprised, why less activity here
IMO **ginkgoTestExplorer** doesn't work with any project, which have `// go:build test` files
Why obvious basic feature as passing flags to *ginkgo* executable not implemented 🤔

**Comment by rufreakde** [comment]
> I'am surprised, why less activity here
> IMO **ginkgoTestExplorer** doesn't work with any project, which have `// go:build test` files
> Why obvious basic feature as passing flags to _ginkgo_ executable not implemented 🤔

This is surprising to me to. Especially for Integration testing this basic feature is a musst to avoid code duplication. And organized projects.

**Comment by darky** [comment]
Use temporary fork https://github.com/darky/ginkgoTestExplorer
LGTM

**Comment by joselitofilho** [comment]
@darky could you open a PR here?

**Comment by darky** [comment]
Sorry no. It's dirty hack. I expect, that you expose it as setting of extension

**Comment by joselitofilho** [comment]
@darky you're right. I will expose it as a setting of extension. Thanks for validating that.

**Comment by zekth** [comment]
@joselitofilho i saw this is stalling in backlog for a few months. I'd be happy to write a PR for this. One thing we can do is adding an `autodetect-tags` based on parsing the file at this step: https://github.com/joselitofilho/ginkgoTestExplorer/blob/3c7dfd00a906f589cf5bf6d8a29d4cfb46c00cbd/src/ginkgoTest.ts#L102

Or we could add a configuration file that adds tags for all tests.

We could also add `extra-tags` fields to resolve this: https://github.com/joselitofilho/ginkgoTestExplorer/issues/55 .

Would that work?

**Comment by rufreakde** [comment]
> "go.testTags"

Why not just check `settings.json` configuration and parse out `"go.testTags"`since these would be set for other possible plugins as the general configuration for test environment.

**Comment by zekth** [comment]
> > @joselitofilho i saw this is stalling in backlog for a few months. I'd be happy to write a PR for this. One thing we can do is adding an `autodetect-tags` based on parsing the file at this step:
> > https://github.com/joselitofilho/ginkgoTestExplorer/blob/3c7dfd00a906f589cf5bf6d8a29d4cfb46c00cbd/src/ginkgoTest.ts#L102
> > 
> > Or we could add a configuration file that adds tags for all tests.
> > We could also add `extra-tags` fields to resolve this: #55 .
> > Would that work?
> 
> Why not just check `settings.json` configuration and parse out `"go.testTags"`since these would be set for other possible plugins as the general configuration for test environment.

In that case we need to add the golang one in the manifest as `extensionDependencies` (ref: https://code.visualstudio.com/api/references/extension-manifest ), or we can do a fallback lookup like:

- check golang extension settings
- check ginkgo settings
