### ISSUE TITLE
ginkgotestexplorer.ginkgoPath does not support variables

### ISSUE THREAD

**Issue by joerocklin** [joselitofilho/ginkgoTestExplorer#52]
I tried setting `ginkgotestexplorer.ginkgoPath` to `"${workspaceFolder}/bin/ginkgo"` and observed the following errors:

```
Checking the Ginkgo executable was installed.
Could not populate the outline view: Error: error running "${workspaceFolder}/bin/ginkgo outline --format=json -" (error code ENOENT)
Ginkgo executable was not found.
```
If I set the option to the full path it does work, so it seems that the issue is specifically with the variable substitution when trying to execute the referenced binary.

**Comment by joselitofilho** [comment]
Changes available from version [v1.0.2](https://github.com/joselitofilho/ginkgoTestExplorer/releases/tag/v1.0.2)
