### ISSUE TITLE
Could not populate the outline view: Error: error running "~/go/bin/ginkgo outline --format=json -" (error code ENOENT)

### ISSUE THREAD

**Issue by devhawk** [joselitofilho/ginkgoTestExplorer#68]
When I click on a test file in the test explorer, I get "Could not populate the outline view" error message and this in the log window:

```
Checking the Ginkgo executable was installed.
Could not populate the outline view: Error: error running "~/go/bin/ginkgo outline --format=json -" (error code ENOENT)
Ginkgo executable already installed. ;)
Checking the Ginkgo executable was installed.
Could not populate the outline view: Error: error running "~/go/bin/ginkgo outline --format=json -" (error code ENOENT)
Ginkgo executable already installed. ;)
```

(Note, I specified the path to ginkgo in my settings file)

**Comment by joselitofilho** [comment]
Hi @devhawk ,

Could you please check if it is related to this: https://github.com/joselitofilho/ginkgoTestExplorer/issues/52? Are you using the latest version [1.0.2](https://github.com/joselitofilho/ginkgoTestExplorer/releases/tag/v1.0.2)?

**Comment by devhawk** [comment]
Yes, looks like #52. If I set `ginkgotestexplorer.ginkgoPath` to `~/go/bin/ginkgo` it fails but it works if I set it to `/home/harry/go/bin/ginkgo` it works.

**Comment by joselitofilho** [comment]
@devhawk
Thanks for the feedback. So shall we close this issue?

**Comment by devhawk** [comment]
Fine by me
